KOHA_TEST_OPAC_BASE = 'https://koha-test.lub.lu.se'
KOHA_TEST_OPAC_LOGIN_PAGE = '/Shibboleth.sso/Login?target=https://koha-test.lub.lu.se/cgi-bin/koha/opac-user.pl'
OPAC_SEARCH_STRING = 'takeaway'
TEST_USER_USERNAME = 'ub2183te'
TEST_USER_PW = 'LUBcat1811'
TEST_USER_FULLNAME = 'UB-Adam'
